version: '2'

services:

  psql:
    image: postgres
    command: /bin/bash
    volumes:
      - /tmp/clubdata:/tmp/clubdata
    environment:
      - PGHOST=pg
      - PGUSER=postgres
      - PGDATABASE=exercises
    command: /bin/bash
    depends_on:
      - pg

  pg:
    image: postgres
    logging:
      options:
        max-size: '50m'
